Insert Into Opcion(Nombre, Estado) Values('Copia de Seguridad de Base de Datos', 1)
Insert Into Opcion(Nombre, Estado) Values('Restaurar Base de Datos', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Usuarios', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Nueva Dosificación', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Proveedores', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Cliente', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Cliente', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Cliente', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Clientes', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Grupos', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Producto', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Producto', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Producto', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Productos', 1)
Insert Into Opcion(Nombre, Estado) Values('Stock de Productos', 1)
Insert Into Opcion(Nombre, Estado) Values('Nueva Compra', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Compra', 1)
Insert Into Opcion(Nombre, Estado) Values('Anular Compra', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Compras', 1)