Insert Into Usuario(CI, Nombres, Apellido_Paterno, Apellido_Materno, Telefono, Nombre_De_Usuario, Clave, Estado) Values('5005402', 'EDWIN', 'ARAOZ', 'NAVARRO', '76195750', 'Admin', '40BD001563085FC35165329EA1FF5C5ECBDBBEEF', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Usuarios', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Proveedores', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Grupo', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Grupos', 1)
