Insert Into Opcion(Nombre, Estado) Values('Nuevo Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Usuario', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista de Usuarios', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Empresa', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Datos de Sucursal', 1)
Insert Into Opcion(Nombre, Estado) Values('Nuevo Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Modificar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Eliminar Proveedor', 1)
Insert Into Opcion(Nombre, Estado) Values('Lista Proveedores', 1)
